name: postgres-ai
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres-ai:v1
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./activate-extension.sql:/docker-entrypoint-initdb.d/0-activate_extension.sql

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=vectordb
      - OPENAI_API_KEY=${OPEN_API_KEY}

  vectorizer-worker:
    image: timescale/pgai-vectorizer-worker:latest
    environment:
       PGAI_VECTORIZER_WORKER_DB_URL: ${WORK_DB_URL}
       OPENAI_API_KEY: ${OPENAO_API_KEY}
    command: [ "--poll-interval", "60s" ]

networks:
  db:
    driver: bridge

