
volumes:
  n8n_storage:
  redis_storage:

x-shared: &shared
  restart: always
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=${POSTGRES_HOST}
    - DB_POSTGRESDB_PORT=${POSTGRES_PORT}
    - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
    - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
    - EXECUTIONS_MODE=queue
    - QUEUE_BULL_REDIS_HOST=redis
    - QUEUE_HEALTH_CHECK_ACTIVE=true
    - N8N_BASIC_AUTH_ACTIVE=false
    - N8N_PROTOCOL=https
    - N8N_PORT=5678
    - VUE_APP_URL_BASE_API=https://${N8N_HOST}
    - WEBHOOK_TUNNEL_URL=https://${N8N_HOST}
    - N8N_RUNNERS_ENABLED=true
    - N8N_PUSH_BACKEND=websocket
    - N8N_EDITOR_BASE_URL=https://${N8N_HOST}
    - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
    - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
  links:
    - redis
  volumes:
     - n8n_storage:/home/node/.n8n
     - ./local-files:/files
  depends_on:
    redis:
      condition: service_healthy

services:
  https-portal:
    image: steveltn/https-portal:latest
    ports:
      - '80:80'
      - '443:443'
    links:
      - n8n
    restart: always
    environment:
      DOMAINS: '${N8N_HOST} -> http://n8n:5678'
      STAGE: ${STAGE:-staging}
      FORCE_RENEW: 'false'
      WEBSOCKET: 'true'
      CUSTOM_NGINX_SERVER_CONFIG_BLOCK: |
         proxy_buffering off;
  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - redis_storage:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    <<: *shared
    image: n8nio/n8n
    ports:
      - 5678:5678

  n8n-worker:
    <<: *shared
    image: n8nio/n8n
    entrypoint: ["n8n", "worker"]
    depends_on:
      - n8n
